### ISSUE TITLE
1.19.2 Forge Conflict with serene-seasons and krypton-reforged

### ISSUE THREAD

**Issue by Danyloz10** [iPortalTeam/ImmersivePortalsModForForge#150]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://www.curseforge.com/minecraft/mc-mods/serene-seasons, https://www.curseforge.com/minecraft/mc-mods/krypton-reforged

### Minecraft version

1.19.2

### Describe the issue

When starting server or single on world generation gives an error, attaching logs.
[crash-2023-12-08_03.13.26-server.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/13634739/crash-2023-12-08_03.13.26-server.txt)

**Comment by ThFortuneTeller** [comment]
same

**Comment by Delfite** [comment]
After disabling Serene Seasons in my modpack to fix the crash, I can confirm that this crash DOES occur on 1.19.2 when Serene Seasons and Immersive Portals are enabled at the same time, in the same pack, using the same steps, with the same error to boot:

``Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method m_183760_ in imm_ptl.mixins.json:common.chunk_sync.MixinChunkMap_C cannot reduce visibiliy of PUBLIC target method``

Please fix!

**Comment by Nick1st** [comment]
See #76. I have zero interest in fixing this, however I do accept pull request.
