### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by M3hdiPG** [iPortalTeam/ImmersivePortalsModForForge#25]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.18

### ImmersivePortals Version

1.4.11-mc1.18.2

### Latest Log

https://gist.github.com/M3hdiPG/a58de6650e18ff844064c44f37dbc37c

### Crash Report (if applicable)

https://gist.github.com/M3hdiPG/b34cdbeab7da3bdba40b79c4c379f62b

### Steps to Reproduce

The error happens when a player joins the server

### What You Expected

I expected to join the server and that everything goes well

### What Happened Instead

the server crashes as soon as i join the serer

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
> According to your testing, does the issue occur with ONLY Immersive Portals mod?
> Yes

Shows log with hundreds of other mods...

Anyway, their is an issue not caused by immptl not allowing you to join: You're simply reaching the maximum size of the connection sync package. This is due to having so many mods. It's a vanilla limitation, nothing I can deal with. You can try a mod increasing that limit, though I wont guaranty it to work with immptl.

About the crash: No support with that, I'm having no time to support Hybrids (Magma). If you can reproduce this on a Forge Server feel free to reopen this issue.
